version: '3'
services:
  nginx: 
    image: nginx:latest
    container_name: mysalon_dev_reverse_proxy
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./nginx/ssl:/etc/nginx/ssl
      - ./nginx/log:/var/log/nginx
    ports:
      - 80:80
      - 443:443
    command: ['nginx', '-g', 'daemon off;']
