export { default as salonServicesFragment } from '../../fragments/services'
export { default as salonBrandsFragment } from './salonBrandsFragment'
export { default as salonReviewsFragment } from './salonReviewsFragment'
export { default as salonAdministratorsFragment } from './salonAdministratorsFragment'
export { default as salonMastersFragment } from './salonMastersFragment'
